#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
autoload -U select-word-style
zle -N select-word-style
bindkey '\ez' select-word-style

bindkey '\ef' forward-word
bindkey '\eb' backward-word

alias sb="mosh devvm2716.vll0.facebook.com -- tmux a"
alias dev="mosh devbig937.prn2.facebook.com -- tmux a"

export PATH=~/.nimble/bin:/opt/ffmpeg/bin:~/bin:$PATH
